include:
  - authentication-microservice/.gitlab-ci.yml
  - example-microservice/.gitlab-ci.yml
  - micro/.gitlab-ci.yml
  - activity-microservice/.gitlab-ci.yml
  - notification-microservice/.gitlab-ci.yml
