image: gradle:latest

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-notifcation-microservice:
  stage: build
  script:
    gradle notifcation-microservice:assemble notifcation-microservice:testClasses

checkStyle-notifcation-microservice:
  stage: staticAnalysis
  script:
    gradle notifcation-microservice:checkstyleMain notifcation-microservice:checkStyleTest
  allow_failure: true


PMD-notifcation-microservice:
  stage: staticAnalysis
  script:
    gradle notifcation-microservice:pmdMain
  allow_failure: true

test-notifcation-microservice:
  stage: test
  script:
    - gradle notifcation-microservice:test notifcation-microservice:jacocoTestReport
    - cat notifcation-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
